name: Deploy MuleSoft Application to CloudHub 2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Danypoint.username="${{ secrets.USER }}" \
          -Danypoint.password="${{ secrets.PASS }}"
    

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>cloudhub2</id>
                <username>76f002fff9c041d78a663b0a26bc008f</username>
                <password>a8055e977df843bCB9fFB5683E52A9BA</password>
              </server>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>777df98bcd084a75bfe4b973a9e53516</username>
                <password>AF10d59Ee8C64EFb85BCc8474b2aA7eD</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build JAR
        run: mvn clean package -DmuleDeploy

  deploydev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>cloudhub2</id>
                <username>76f002fff9c041d78a663b0a26bc008f</username>
                <password>a8055e977df843bCB9fFB5683E52A9BA</password>
              </server>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>777df98bcd084a75bfe4b973a9e53516</username>
                <password>AF10d59Ee8C64EFb85BCc8474b2aA7eD</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Deploy to dev
        run: |
          mvn deploy -DmuleDeploy -DskipMunitTests \
            -Danypoint.username=76f002fff9c041d78a663b0a26bc008f \
            -Danypoint.password=a8055e977df843bCB9fFB5683E52A9BA \
            -Danypoint.platform.client_id=777df98bcd084a75bfe4b973a9e53516 \
            -Danypoint.platform.client_secret=AF10d59Ee8C64EFb85BCc8474b2aA7eD \
            -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
            -Denv=Dev \
            -Dappname=githubaction

  
